apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: demonamespace
  name: demosrvact

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demonamespace
  name: api-reader-core
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demonamespace
  name: api-reader-app
rules:
- apiGroups: ["apps"] 
  resources: ["statefulsets", "replicasets", "replicationcontrollers", "deployments", "daemonsets", "jobs", "cronjobs", "services", "controllerrevisions"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: demonamespace
  name: demosrvact-api-reader-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-reader-core
subjects:
- kind: ServiceAccount
  name: demosrvact
  namespace: demonamespace

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: demonamespace
  name: demosrvact-api-reader-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-reader-app
subjects:
- kind: ServiceAccount
  name: demosrvact
  namespace: demonamespace



